### ISSUE TITLE
编译时间的问题？

### ISSUE THREAD

**Issue by citrusjunoss** [godbasin/wxapp-typescript-demo#11]
![image](https://user-images.githubusercontent.com/18432488/70014223-18f20700-15b5-11ea-861a-b08fd75fa380.png)
编译的时间有办法优化么？ 比如说npm 打包的时间，目前所有流走完加上微信的编译要10几秒。有点慢了

**Comment by godbasin** [comment]
目前还没有很好的思路，我自己一般把npm去掉，用工具的npm构建，版本要求目前看也不算高。

**Comment by godbasin** [comment]
最新版去掉了gulp打包npm，建议使用工具的npm构建
