### ISSUE TITLE
项目运行报错

### ISSUE THREAD

**Issue by xsdream** [godbasin/wxapp-typescript-demo#14]
![image](https://user-images.githubusercontent.com/31870384/79823020-34737800-83c5-11ea-9a31-286f6bd856cc.png)
npm install
npm run dev
小程序开发工具运行报错
miniprogram-watch 依赖已经安装。

**Comment by xsdream** [comment]
作者大佬可以提供下微信/qq，方便沟通吗。

**Comment by godbasin** [comment]
感觉可以重启下开发工具试试

**Comment by marsend** [comment]
小程序开发工具，点击 工具 -> Build npm
