### ISSUE TITLE
你好，我有个关于typescript做微信小程序的问题。

### ISSUE THREAD

**Issue by w0330t** [godbasin/wxapp-typescript-demo#4]
我是一个前端新手，我也不确定在这里提一个issue合适不合适。请见谅
具体就是说自定义组件Component的methods的问题
就拿您的代码举一个例子。
![image](https://user-images.githubusercontent.com/4970238/61990840-5e884b80-b07a-11e9-8c6a-3000edf880bb.png)
我在您的代码onTap里面加了一个参数event，然后IDE就在mathod那里给我报错，
`TS2322: Type '{ onTap(event: any): void; }' is not assignable to type '{ [methodName: string]: (this: WxComponent) => any; }'.
  Property 'onTap' is incompatible with index signature.
    Type '(event: any) => void' is not assignable to type '(this: WxComponent) => any'.`
微信官方提供的接口这个参数应该是一个`this: WxComponent`，所以这个event属于一个类型错误？
但是我并没有找到其他可以取得这个事件的办法，我看您博客上也有类似的写法，
虽然可以直接编译运行……
IDE的话，我用vs和webstorm都会报这个错误。
我想问一下这个是IDE的问题还是我有啥库没导入，如何解决这个错误？
不胜感激。

**Comment by godbasin** [comment]
这个是[官方的typing](https://github.com/wechat-miniprogram/api-typings)，然后这里也有人提了相关的[issues](https://github.com/wechat-miniprogram/api-typings/issues/27)。
你可以自己改一下 component 的这个定义，我们目前随便改了个这样用着：
``` ts
  methods?: {
    [methodName: string]: (e: any, ...args) => any;
  };
```
仅供参考

**Comment by w0330t** [comment]
我知道这个typing是官方的，所以才不那么确定，总之谢谢你，我准备用这个demo做框架做点小东西，如果有什么问题还请多多帮忙。

**Comment by godbasin** [comment]
> 我知道这个typing是官方的，所以才不那么确定，总之谢谢你，我准备用这个demo做框架做点小东西，如果有什么问题还请多多帮忙。

嗯，官方的typing库还有待完善的地方，你可以根据API文档看看确认就好。
