### ISSUE TITLE
又来打搅了

### ISSUE THREAD

**Issue by w0330t** [godbasin/wxapp-typescript-demo#6]
被删小姐姐好，又来打搅你了
builtPath的路径被我更改之后路径后编译的时候卡住了
![image](https://user-images.githubusercontent.com/4970238/62420826-6758cd00-b6cb-11e9-90f6-63afbda53c2e.png)
还有，微信typing库好像更新了，这边要不要更新一下？

**Comment by godbasin** [comment]
编译卡住没有遇到，请描述清楚。typing更新了
