### ISSUE TITLE
组件的事件参数

### ISSUE THREAD

**Issue by Racaly** [godbasin/wxapp-typescript-demo#7]
请问在watch组件的button 上添加事件参数后ontap函数该如何写，

**Comment by godbasin** [comment]
事件函数要传参，需要在元素上绑定`dataset`，然后通过`event.currentTarget`来获取，可以参考[dataset 文档](https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxml/event.html#dataset)。

**Comment by Racaly** [comment]
不不，我并不是这个意思，我知道如何绑定事件函数。如图：
![image](https://user-images.githubusercontent.com/18939332/63081934-7e26db80-bf77-11e9-8381-9a5bac37aeb3.png)
在javascript中这样写并没有什么问题。在ts中编译后实际运行也是可行的，但是我的ide(vs code)报错，提示我handletype并不兼容method:{methodName:string:(this:wxComponent:()=>any)},且handletype中的this不存在setData方法。如果我修改成handletype(),删除了e,不在接受参数，一切变正常了。当然这些ide的报错并不影响编译及小程序。但是因为ide报错，我想我在这里的理解和写法肯定是不对的，所以我想如何才能解决这个问题。

**Comment by godbasin** [comment]
可以参考 [#4](https://github.com/godbasin/wxapp-typescript-demo/issues/4)
看了下最新版本是修复了这问题的，可以拉一下代码，我先关闭了

**Comment by Racaly** [comment]
谢谢
