### ISSUE TITLE
请问此项目目录结构如何支持小程序npm构建？

### ISSUE THREAD

**Issue by Observer-L** [godbasin/wxapp-typescript-demo#8]
无法按照[官网文档](https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html)实现。

**Comment by Observer-L** [comment]
ok，需要把依赖copy到dist

**Comment by godbasin** [comment]
次项目目录不需要进行npm构建，使用npm构建有基础库版本`2.2.1`的要求。
